### ISSUE TITLE
[Feature]分布式交换机和大版本升级

### ISSUE THREAD

**Issue by wugh888** [KubeOperator/KubeOperator#505]
**请描述您的需求或者改进建议.**
我再使用中遇到四个问题：
1.vSphere不支持分布式交换机（创建完机器，自己手动改网络）
2.不支持大版本升级（公有云托管的和rancher创建的都是支持跨大版本的）
3.用了rook-ceph，新增节点的话能自动扩展存储空间吗？（网上看好像要自己进去敲命令行扩展）
![2d5ee262b9e73f3b6b22f4dbec4f42c](https://user-images.githubusercontent.com/17397052/186577866-23f68579-674c-427b-a6c8-96d35b80a090.jpg)
4.容器网络使用cilium的话，新增节点会出现这个报错（好像是yaml里的某个参数类型有问题）
![b0c79a6f0e9ad9fb203ba8bab2d7ba5](https://user-images.githubusercontent.com/17397052/186577946-7b9679f5-42c0-4dd1-8dd0-c4d423763091.jpg)

**Comment by wanghe-fit2cloud** [comment]
1、已修复不支持分布式交换机的问题，近期会发布版本
2、不支持跨大版本升级
3、新增节点不能自动扩展存储空间
4、修改部署机 /opt/kubeoperator/data/kobe/project/ko/91-add-worker-07-network.yml，修改后内容：
```yaml
- hosts:
  - kube-master
  - kube-worker
  - new-worker
  gather_facts: false ### 此列删除
  roles:
  - plugins/network-plugins/network-prepare

- hosts: kube-master[0]
  gather_facts: false
  roles:
  - plugins/network-plugins/network-deploy
```
